In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [2]:
mitbihTestdf = pd.read_csv("mitbih_test.csv")
mitbihTraindf = pd.read_csv("mitbih_train.csv")
ptbdbNormaldf = pd.read_csv("ptbdb_normal.csv")
ptbdbAbnormaldf = pd.read_csv("ptbdb_abnormal.csv")

In [3]:
mitbihTraindf

,9.779411554336547852e-01,9.264705777168273926e-01,6.813725233078002930e-01,2.450980395078659058e-01,1.544117629528045654e-01,1.911764740943908691e-01,1.519607901573181152e-01,8.578431606292724609e-02,5.882352963089942932e-02,4.901960864663124084e-02,...,0.000000000000000000e+00.79,0.000000000000000000e+00.80,0.000000000000000000e+00.81,0.000000000000000000e+00.82,0.000000000000000000e+00.83,0.000000000000000000e+00.84,0.000000000000000000e+00.85,0.000000000000000000e+00.86,0.000000000000000000e+00.87,0.000000000000000000e+00.88
0,0.960114,0.863248,0.461538,0.196581,0.094017,0.125356,0.099715,0.088319,0.074074,0.082621,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.000000,0.659459,0.186486,0.070270,0.070270,0.059459,0.056757,0.043243,0.054054,0.045946,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.925414,0.665746,0.541436,0.276243,0.196133,0.077348,0.071823,0.060773,0.066298,0.058011,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.967136,1.000000,0.830986,0.586854,0.356808,0.248826,0.145540,0.089202,0.117371,0.150235,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.927461,1.000000,0.626943,0.193437,0.094991,0.072539,0.043178,0.053541,0.093264,0.189983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87548,0.807018,0.494737,0.536842,0.529825,0.491228,0.484211,0.456140,0.396491,0.284211,0.136842,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87549,0.718333,0.605000,0.486667,0.361667,0.231667,0.120000,0.051667,0.001667,0.000000,0.013333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87550,0.906122,0.624490,0.595918,0.575510,0.530612,0.481633,0.444898,0.387755,0.322449,0.191837,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87551,0.858228,0.645570,0.845570,0.248101,0.167089,0.131646,0.121519,0.121519,0.118987,0.103797,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0


In [4]:
mitbihTestdf

,1.000000000000000000e+00,7.582644820213317871e-01,1.115702465176582336e-01,0.000000000000000000e+00,8.057851344347000122e-02,7.851240038871765137e-02,6.611569970846176147e-02,4.958677664399147034e-02,4.752065986394882202e-02,3.512396663427352905e-02,...,0.000000000000000000e+00.56,0.000000000000000000e+00.57,0.000000000000000000e+00.58,0.000000000000000000e+00.59,0.000000000000000000e+00.60,0.000000000000000000e+00.61,0.000000000000000000e+00.62,0.000000000000000000e+00.63,0.000000000000000000e+00.64,0.000000000000000000e+00.65
0,0.908425,0.783883,0.531136,0.362637,0.366300,0.344322,0.333333,0.307692,0.296703,0.300366,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.730088,0.212389,0.000000,0.119469,0.101770,0.101770,0.110619,0.123894,0.115044,0.132743,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.000000,0.910417,0.681250,0.472917,0.229167,0.068750,0.000000,0.004167,0.014583,0.054167,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.570470,0.399329,0.238255,0.147651,0.000000,0.003356,0.040268,0.080537,0.070470,0.090604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.000000,0.923664,0.656489,0.195929,0.111959,0.175573,0.122137,0.050891,0.035623,0.055980,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21886,0.928736,0.871264,0.804598,0.742529,0.650575,0.535632,0.394253,0.250575,0.140230,0.102299,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21887,0.802691,0.692078,0.587444,0.446936,0.318386,0.189836,0.118087,0.077728,0.112108,0.152466,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21888,1.000000,0.967359,0.620178,0.347181,0.139466,0.089021,0.103858,0.100890,0.106825,0.100890,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21889,0.984127,0.567460,0.607143,0.583333,0.607143,0.575397,0.575397,0.488095,0.392857,0.238095,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0


In [5]:
ptbdbNormaldf

,1.000000000000000000e+00,9.003241658210754395e-01,3.585899472236633301e-01,5.145867168903350830e-02,4.659643396735191345e-02,1.268233358860015869e-01,1.333063244819641113e-01,1.191247999668121338e-01,1.106158867478370667e-01,1.130470037460327148e-01,...,0.000000000000000000e+00.56,0.000000000000000000e+00.57,0.000000000000000000e+00.58,0.000000000000000000e+00.59,0.000000000000000000e+00.60,0.000000000000000000e+00.61,0.000000000000000000e+00.62,0.000000000000000000e+00.63,0.000000000000000000e+00.64,0.000000000000000000e+00.65
0,1.000000,0.794681,0.375387,0.116883,0.000000,0.171923,0.283859,0.293754,0.325912,0.345083,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.909029,0.791482,0.423169,0.186712,0.000000,0.007836,0.063032,0.077002,0.074957,0.077342,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.000000,0.478893,0.056760,0.064176,0.081289,0.072732,0.055619,0.048774,0.054478,0.041643,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.000000,0.867238,0.201360,0.099349,0.141336,0.120934,0.108516,0.096393,0.093436,0.100828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.948983,0.505265,0.004176,0.022513,0.059550,0.107298,0.110385,0.111293,0.116558,0.118192,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4040,1.000000,0.929586,0.503550,0.293491,0.169822,0.159763,0.130769,0.125444,0.137278,0.111243,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4041,1.000000,0.637579,0.154837,0.061983,0.088965,0.083374,0.065143,0.057365,0.060039,0.060039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4042,1.000000,0.872574,0.465071,0.232212,0.126132,0.155886,0.174644,0.190168,0.203752,0.168823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4043,0.915983,0.529373,0.288406,0.144536,0.171802,0.180669,0.177566,0.176458,0.178896,0.180448,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [6]:
ptbdbAbnormaldf

,9.322328567504882812e-01,8.696785569190979004e-01,8.861859440803527832e-01,9.296264052391052246e-01,9.087749719619750977e-01,9.339704513549804688e-01,8.010425567626953125e-01,7.497828006744384766e-01,6.872285008430480957e-01,6.350998878479003906e-01,...,0.000000000000000000e+00.117,0.000000000000000000e+00.118,0.000000000000000000e+00.119,0.000000000000000000e+00.120,0.000000000000000000e+00.121,0.000000000000000000e+00.122,0.000000000000000000e+00.123,0.000000000000000000e+00.124,0.000000000000000000e+00.125,1.000000000000000000e+00.1
0,1.000000,0.606941,0.384181,0.254237,0.223567,0.276836,0.253430,0.184826,0.153349,0.121872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.000000,0.951613,0.923963,0.853303,0.791859,0.734255,0.672043,0.685100,0.670507,0.667435,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.977819,0.899261,0.230129,0.032348,0.142329,0.223660,0.328096,0.367837,0.381701,0.389094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.935618,0.801661,0.805815,1.000000,0.722741,0.480789,0.454829,0.319834,0.266874,0.308411,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.925265,0.433352,0.073620,0.079197,0.136643,0.182934,0.182934,0.182376,0.196877,0.203569,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10500,0.981409,1.000000,0.559171,0.287093,0.196639,0.204862,0.215946,0.243833,0.242760,0.250268,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10501,0.906250,0.922379,0.878024,0.810484,0.712702,0.667339,0.608871,0.527218,0.480847,0.442540,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10502,1.000000,0.867971,0.674122,0.470332,0.296987,0.169307,0.077664,0.081392,0.074868,0.089779,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10503,1.000000,0.984672,0.658888,0.556394,0.446809,0.395790,0.315260,0.276367,0.261039,0.258522,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0


### Transfer Learning Goal
- To train a model on mitbih data
- Test the model on mitbih test data
- Remove last two layers and add two layers at the end for fine tuning as per paper
- Train these last two layers only and check accuracy on ptbdb data

### Pre processing data
- One hot encoding is also needed for 5 classes

In [7]:
m,n = mitbihTraindf.shape
print(m,n)

87553 188


In [8]:
train_data = mitbihTraindf.to_numpy()
train_data = train_data.T

In [9]:
train_data

array([[0.96011394, 1.        , 0.92541438, ..., 0.90612245, 0.85822785,
        0.90150636],
       [0.86324787, 0.65945947, 0.66574585, ..., 0.62448978, 0.64556962,
        0.84588647],
       [0.46153846, 0.18648648, 0.54143649, ..., 0.59591836, 0.84556961,
        0.80069524],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 4.        , 4.        ,
        4.        ]])

#### Now our row has the labels
##### Classes: ['N': 0, 'S': 1, 'V': 2, 'F': 3, 'Q': 4]

In [10]:
trainY = train_data[-1]
print("Size : 1 x",len(trainY))
trainY

Size : 1 x 87553


array([0., 0., 0., ..., 4., 4., 4.])

In [11]:
trainX = train_data[:n-1]
print("Size : ",len(trainX),"x",len(trainX[0]))
trainX

Size :  187 x 87553


array([[0.96011394, 1.        , 0.92541438, ..., 0.90612245, 0.85822785,
        0.90150636],
       [0.86324787, 0.65945947, 0.66574585, ..., 0.62448978, 0.64556962,
        0.84588647],
       [0.46153846, 0.18648648, 0.54143649, ..., 0.59591836, 0.84556961,
        0.80069524],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

#### So now we have proper data split
- Each column must be passed as input, i.e. 187 inputs are for one run/test case

### Preprocessing test data as well

In [12]:
m,n = mitbihTestdf.shape
print(m,n)

21891 188


In [13]:
test_data = mitbihTestdf.to_numpy()
test_data = test_data.T
print(test_data)
print(n,"x",m)

[[0.90842491 0.73008847 1.         ... 1.         0.98412699 0.97396964]
 [0.7838828  0.21238938 0.91041666 ... 0.96735907 0.5674603  0.91323209]
 [0.53113556 0.         0.68124998 ... 0.62017804 0.60714287 0.86550975]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 4.         4.         4.        ]]
188 x 21891


In [14]:
testY = test_data[-1]
print("Size : 1 x ",len(testY))
testY

Size : 1 x  21891


array([0., 0., 0., ..., 4., 4., 4.])

In [15]:
testX = test_data[0:n-1]
print("Size : ",len(testX),"x",len(testX[0]))
testX

Size :  187 x 21891


array([[0.90842491, 0.73008847, 1.        , ..., 1.        , 0.98412699,
        0.97396964],
       [0.7838828 , 0.21238938, 0.91041666, ..., 0.96735907, 0.5674603 ,
        0.91323209],
       [0.53113556, 0.        , 0.68124998, ..., 0.62017804, 0.60714287,
        0.86550975],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

### MLP Architecture (187 -> 512 -> 256 -> 128 -> 64 -> 32 -> 16 -> 5)
- We need last two layer as configurable and removable so previous layers must encode enough features
- Input layer is 187 since 187 features, 
- Output layer is 5 since 5 classes
- Let's keep 5 hiddenlayers with last two removable
- So (187 -> 512 -> 256 -> 128 -> 64 -> 32 -> 16 -> 5)
- We can provide 64 features to our ptbdb dataset and train a 8 -> 2 layers next for fine tuning

### Init Parameters

In [16]:
#Using He Init with ReLU
def init_params():
    W1 = np.random.randn(512,187)*np.sqrt(2/187)
    b1 = np.zeros((512,1))
    W2 = np.random.randn(256,512)*np.sqrt(2/512)
    b2 = np.zeros((256,1))
    W3 = np.random.randn(128,256)*np.sqrt(2/256)
    b3 = np.zeros((128,1))
    W4 = np.random.randn(64,128)*np.sqrt(2/128)
    b4 = np.zeros((64,1))
    W5 = np.random.randn(32,64)*np.sqrt(2/64)
    b5 = np.zeros((32,1))
    W6 = np.random.randn(16,32)*np.sqrt(2/32)
    b6 = np.zeros((16,1))
    W7 = np.random.randn(5,16)*np.sqrt(2/16)
    b7 = np.zeros((5,1))
    
    wArr = [W1,W2,W3,W4,W5,W6,W7]
    bArr = [b1,b2,b3,b4,b5,b6,b7]
    
    return wArr,bArr

In [17]:
init_params()

([array([[-0.09292099, -0.05958299, -0.01890939, ...,  0.18373212,
          -0.02194029,  0.02667523],
         [ 0.07448798, -0.13763199, -0.17194299, ...,  0.06724868,
           0.02291123, -0.09707481],
         [-0.05980745,  0.06764881,  0.12806415, ..., -0.00224856,
          -0.09915808,  0.10569533],
         ...,
         [ 0.11087726, -0.03776509,  0.02168396, ...,  0.04293583,
           0.04241729,  0.07338053],
         [ 0.06609759, -0.09183552,  0.0586907 , ...,  0.01480796,
          -0.08323748,  0.18756191],
         [ 0.22009895,  0.0017983 ,  0.02576369, ...,  0.15609642,
          -0.0082159 , -0.00759523]]),
  array([[-3.37992434e-02, -3.64958827e-02, -3.23917908e-02, ...,
          -8.13024886e-02,  1.24726331e-01,  9.24394249e-02],
         [-9.30231641e-03, -1.48916129e-02, -2.20560835e-02, ...,
          -7.88080027e-02,  5.83482793e-02, -1.68233512e-04],
         [-5.86025103e-02, -1.63071384e-02, -2.94438393e-02, ...,
          -1.79277004e-02, -7.41363829

### Utility Functions

In [18]:
def ReLU(Z):
    return np.maximum(Z,0)

def derivative_ReLU(Z):
    return Z>0

def softmax(Z):
    expZ = np.exp(Z-np.max(Z,axis = 0,keepdims = True))
    return expZ/np.sum(expZ,axis =0 ,keepdims = True)

def one_hot(Y):
    #We need 5 classes
    size = Y.size
    one_hot_Y = np.zeros((5,size))
    for index,val in enumerate(Y):
        one_hot_Y[int(val)][index]=1
    
    return one_hot_Y

In [19]:
one_hot(trainY)

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]])

### Main Functions

In [20]:
def forward_pass(X,wArr,bArr):
    
    #Number of Layers
    n = len(wArr)
    
    activationVal = X
    zArr = []
    aArr = []
    for i in range(n):
        
        zArr.append(wArr[i].dot(activationVal) + bArr[i])
        if i!=n-1:
            activationVal = ReLU(zArr[-1])
            aArr.append(activationVal)
        else:
            activationVal = softmax(zArr[-1])
            aArr.append(activationVal)
            
#     for index,arr in enumerate(aArr):
#         print(index," : ",len(arr),len(arr[0]))
        
    return zArr,aArr

In [21]:
def backward_pass(X,Y,zArr,aArr,wArr):
    
    m = Y.size
    
    #Number of Layers
    n = len(wArr)
    
    dZArr,dWArr,dbArr = [],[],[]
    
    one_hot_Y = one_hot(Y)
    
    for i in range(n):
        
        if i==0:
            dZArr.append(aArr[-1] - one_hot_Y)
        else:
            dZArr.append(wArr[n-i].T.dot(dZArr[-1]) * derivative_ReLU(zArr[n-i-1]))
        
        if i==n-1:
            dWArr.append(1/m * dZArr[-1].dot(X.T))
        else:
            dWArr.append(1/m * dZArr[-1].dot(aArr[n-i-2].T))
            
        dbArr.append(1/m * np.sum(dZArr[-1], axis = 1, keepdims = True))
            
    return dWArr[::-1],dbArr[::-1]

In [22]:
def update_params(alpha,dWArr,dbArr,wArr,bArr):
    
    #Number of Layers
    n = len(wArr)
    
    for i in range(n):
#         print("Debug w : ",len(wArr[i]),"x",len(wArr[i][0]),"Debug dw : ",len(dWArr[i]),"x",len(dWArr[i][0]))
        wArr[i] -= alpha * dWArr[i]
        bArr[i] -= alpha * dbArr[i]
        
    return wArr,bArr

### Driver Function

In [23]:
def get_prediction(A):
    return np.argmax(A,0)

def get_accuracy(prediction,Y):
    #The Y values we get are letters
    
    return np.sum(prediction==Y)/len(Y)

def sgd(X,Y,alpha,epochs):
    
    wArr,bArr = init_params()
    batch_size = 1000
        
    for epoch_cnt in range(epochs):
        
        shuffled_indices = np.random.permutation(Y.size)
        X_shuffled = X[:, shuffled_indices]
        Y_shuffled = Y[shuffled_indices]
    
        for start in range(0,Y.size,batch_size):

            end = start + batch_size

            X_batch = X_shuffled[:,start:end]
            Y_batch = Y_shuffled[start:end]

            #Perform Forward Pass
            zArr, aArr = forward_pass(X_batch,wArr,bArr)

            #Perform Backward Pass
            dWArr,dbArr = backward_pass(X_batch,Y_batch,zArr,aArr,wArr)

            #Update Parameters
            wArr,bArr = update_params(alpha,dWArr,dbArr,wArr,bArr)
            
        print("Epoch : ",epoch_cnt)
        prediction = get_prediction(aArr[-1])
        print(get_accuracy(prediction,Y_batch))
            
    return wArr,bArr

In [24]:
wArr,bArr = sgd(trainX,trainY,0.01,50)

Epoch :  0
0.8137432188065099
Epoch :  1
0.8191681735985533
Epoch :  2
0.8589511754068716
Epoch :  3
0.9005424954792043
Epoch :  4
0.8969258589511754
Epoch :  5
0.8933092224231465
Epoch :  6
0.9095840867992767
Epoch :  7
0.9294755877034359
Epoch :  8
0.9240506329113924
Epoch :  9
0.918625678119349
Epoch :  10
0.9421338155515371
Epoch :  11
0.9367088607594937
Epoch :  12
0.9385171790235082
Epoch :  13
0.9222423146473779
Epoch :  14
0.945750452079566
Epoch :  15
0.9403254972875226
Epoch :  16
0.9529837251356239
Epoch :  17
0.9403254972875226
Epoch :  18
0.9385171790235082
Epoch :  19
0.9204339963833634
Epoch :  20
0.9511754068716094
Epoch :  21
0.9475587703435805
Epoch :  22
0.9638336347197106
Epoch :  23
0.945750452079566
Epoch :  24
0.9421338155515371
Epoch :  25
0.9620253164556962
Epoch :  26
0.9620253164556962
Epoch :  27
0.9602169981916817
Epoch :  28
0.9439421338155516
Epoch :  29
0.9529837251356239
Epoch :  30
0.9584086799276673
Epoch :  31
0.9584086799276673
Epoch :  32
0.9764918

### 96.925 % Accuracy !!!

In [25]:
def make_prediction(X,wArr,bArr):
    
    #Perform Forward Pass
    _,aArr = forward_pass(X,wArr,bArr)
    A = aArr[-1]
    
    return get_prediction(A)

In [26]:
predictions = make_prediction(testX,wArr,bArr)
print(predictions.size,predictions,testY)
get_accuracy(predictions,testY)

21891 [0 0 0 ... 4 4 4] [0. 0. 0. ... 4. 4. 4.]


0.965556621442602

### 96.55 % Accuracy !!!
- No signs of overfitting

### TRANSFER LEARNING IMPLEMENTATION
- Use the earlier layers till 32, so 32 features of ECG are not getting trained again
- The last two layers of 8-> 2 need to be added, where 2 is the output layer